server:
  port: 7979
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: system
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: Aves.java@gmail.com
    password: 52646006
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true